Add rs.refdata.get as subpermission to ui-request.view
I _hope_ this will fix a bug reported by Kristen on Slack, where users
without edit permissions have started being confronted by an error
when browsing requests:

	ERROR: in module @folio/supply, operation GET on resource
	'refdatavalues' failed, saying: Access requires permission:
	rs.refdata.get

But of course it's impossible to tell whether it will, and we won't
know until the next complete rebuild of the server, due to
MODPERMS-34.

Fingers crossed.